
/*
 CREATE TABLE AUTHORS(
	AUTHOR_ID INT NOT NULL AUTO_INCREMENT, 
	NAME VARCHAR(50),
	SURNAME VARCHAR(50),
	PRIMARY KEY(AUTHOR_ID)
);
*/
DROP TABLE IF EXISTS PRODUCTS_COMPONENTS, ORDER_ITEMS, ORDERS, COMPONENTS, PRODUCTS CASCADE;

CREATE TABLE COMPONENTS(
	COMPONENT_ID INT  NOT NULL AUTO_INCREMENT, 
	TITLE VARCHAR(200), 
	DESCRIPTION BLOB, 
	PRICE NUMERIC(5,2),
	QTY INT,
	PRIMARY KEY(COMPONENT_ID)
	/* FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)*/
);

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT  NOT NULL AUTO_INCREMENT, 
	TITLE VARCHAR(200), 
	DESCRIPTION BLOB, 
	PRICE NUMERIC(5,2), 
	PRIMARY KEY(PRODUCT_ID)
	-- FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- Many to many relationship between products and components.

CREATE TABLE PRODUCTS_COMPONENTS(
	ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_ID INT NOT NULL,
	COMPONENT_ID INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
	FOREIGN KEY(COMPONENT_ID) REFERENCES COMPONENTS(COMPONENT_ID)
);


-- ONE ORDER MAY CONTAIN A LOT OF PRODUCTS
-- CREATE UNIQUE SEQUENCE ORDER_ID_SEQ;

CREATE TABLE ORDERS(
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	BUYER_NAME VARCHAR(100),
	SHIPPING_ADRESS VARCHAR(100),
	SHIPPING_ZIPCODE VARCHAR(10),
	SHIPPING_CITY VARCHAR(30),
	PRIMARY KEY(ORDER_ID)
);

-- EACH DISTINCT ORDER ITEMS	
-- CREATE UNIQUE SEQUENCE ORDER_ITEM_ID_SEQ;

CREATE TABLE ORDER_ITEMS(
	ORDER_ITEM_ID INT NOT NULL AUTO_INCREMENT,
	ORDER_ID INT,
	PRODUCT_ID INT,
	QUANTITY INT,
	PRIMARY KEY(ORDER_ITEM_ID),
	FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
	FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO PRODUCTS(PRODUCT_ID, TITLE, DESCRIPTION, PRICE) 
	VALUES(1, 'HAVREFLARN', 'Ett mumsigt HAVREFLARN av högsta kvalité', 600);
INSERT INTO PRODUCTS(PRODUCT_ID, TITLE, DESCRIPTION, PRICE) 
	VALUES(2, 'CLASSIC DATA STRUCTURES IN C++', 'BUDD EXPLAINS SEVERAL DATA STRUCTURES THAT ARE COMMIN IN C++', 550);
INSERT INTO PRODUCTS(PRODUCT_ID, TITLE, DESCRIPTION, PRICE) 
	VALUES(3, 'CLASSIC DATA STRUCTURES IN JAVA', 'BUDD EXPLAINS SEVERAL DATA STRUCTURES THAT ARE COMMIN IN JAVA', 650);
INSERT INTO PRODUCTS(PRODUCT_ID, TITLE, DESCRIPTION, PRICE) 
	VALUES(4, 'SPECIAL EDITION USING JAVA SERVER PAGES', 'A QUITE EXTENSIVE BOOK ABOUT WEB DEVELOPMENT USING JAVA SERVER PAGES AND JAVA SERVLETS', 400);
INSERT INTO PRODUCTS(PRODUCT_ID, TITLE, DESCRIPTION, PRICE) 
	VALUES(5, 'C: HOW TO PROGRAM', 'AN INTRODUCTION TO C-PROGRAMMING.', 430);

INSERT INTO COMPONENTS(COMPONENT_ID, TITLE, DESCRIPTION, PRICE, QTY)
	VALUES(1, 'HAVRE', 'Havre av högsta kvalité', 10, 10),
	(2, 'FLARN', 'Flarn av högsta kvalité', 25, 12);

INSERT INTO PRODUCTS_COMPONENTS(PRODUCT_ID, COMPONENT_ID)
	VALUES(1,1),
	(1,2);